Unsupported file format
zero-to-mastery/visual-music pull request #27
Opened 2019-10-01 12:10 UTC by lucierabahi

- I created a stateless `UnsupportedFileFormat.component `
- Added a background image which wasn't mentioned on the Trello card but we talk about it with Neha  and Arnas. I picked up this image but it can be changed if you guys don't like it.
- Created a `mixins.css` file in the `globalScss` folder with mixins for the overlay and for flexbox settings, as I think both will often be used
- Button isn't SVG. I wrote this criteria but I'm not sure it's relevant. Please give me your opinion, I'll change it if necessary.
- Added media queries with breakpoints at 320px, 568px and 768px. 
I think that's it.

2019-10-01 17:31 UTC, ArnasDickus commented on src/index.js
> +ReactDOM.render(<UnsupportedFileFormat />, document.getElementById('root'));
I don't think you should add an Unsupported file format in index.js. It should be put as a component in-app.js

2019-10-01 17:39 UTC, ArnasDickus requested changes
Hello, so I was expecting to have an unsupported file format. Popup appear on the page. Right now it looks more as a page.

So the problem is that this project doesn't have a SPA routing [react routing](https://trello.com/c/iMs6MLFn/102-add-react-routing). So player bar and visualizer in app.js is not the correct place. However, until when let's leave it as it is.

Here's my suggestions:
1) Add unsupported file format component in app.js
2) Remove the background since this popup is going to appear in the center while the user is trying to import the song.
3) Connect it with player bar add music button. If the format is not supported this popup should appear.

2019-10-02 06:37 UTC, lucierabahi commented
Yes, it should be only the /pop-upbox component replacing the "upload song" box, on the same page.
Index.js was for testing my component while developing, forgot to move it to app.js before making the PR, sorry.
Ok for background, ok for player bar. 
Thank you for the review.

2019-10-02 18:17 UTC, ArnasDickus commented
Testing travis.

2019-10-08 10:40 UTC, closed without merging