first PR for PlayerBar component.
zero-to-mastery/visual-music pull request #49
Opened 2019-10-13 04:42 UTC by Askat08

Multiple commits done in `src/pages/App` and `src/components/PlayerBar` folders. 
In `src/pages/App` folder:

- `getTime` method has been created for audio duration converter in proper format ( eg: 0:00 )

- `audio` html Element added with attribute `ref` pointing to `this.player` prop.

- `onFileUpload` method had modified and added some code to create url using `URL.createObjectURL` method and passed uploaded `FILE`, then firing `loadedmetadata` event to get access audio duration and `setState`  `duration` prop. 

In `src/components/PlayerBar` folder:

- Player audio bar duration time changed and displaying uploaded audio file duration.

I want to make sure if this approach efficient enough before I can continue. Looks workable to me at this point but i can be wrong. Please take a look at my commits and I'd love to see some feedback. Thank you.

2019-10-13 04:45 UTC, Askat08 commented
Trello task link [https://trello.com/c/KDIpnjgf/104-improve-player-bar](url)

2019-10-13 15:01 UTC, ArnasDickus requested changes
Thanks for adding PR. Your way seems to work. However I have one issue.

I found this react tutorial, might be useful. [audio player tutorial](https://dev.to/ma5ly/lets-make-a-little-audio-player-in-react-p4p)

2019-10-13 15:01 UTC, ArnasDickus commented on src/pages/App/App.js
> +        let audio = document.querySelector('#audio');
I would like to avoid using document.querrySelector to react. Because it's not a react way, and instead use Refs.
[refs vs document.get](https://stackoverflow.com/questions/37273876/reactjs-this-refs-vs-document-getelementbyid)
[refs react documentation](https://reactjs.org/docs/refs-and-the-dom.html)

2019-10-13 18:53 UTC, Askat08 commented on src/pages/App/App.js
> +        let audio = document.querySelector('#audio');
Hi @ArnasDickus , I found that audio player tutorial very useful and borrowed `getTime` method from it. And thank you for letting me know that `document.querySelector` isn't React way, good to know. Appropriate changes will be done now.

2019-10-15 18:51 UTC, ArnasDickus approved these changes
So I have no issues here. Do I merge this PR or are you going to add more functionality to the player bar?

2019-10-16 00:46 UTC, Askat08 commented
Hi @ArnasDickus, thank you for your time. Currently I'm working on displaying `currentTime` audio playback position.

2019-10-19 20:40 UTC, ArnasDickus approved these changes
I'm guessing you're not planning on updating this PR. Merging it

2019-10-19 20:40 UTC, merged

2019-10-21 04:06 UTC, Askat08 commented
Sorry @ArnasDickus for that did not keep posting you about playerBar progress. I tried a few options. I tried `useEffect` to keep update song `currentTime`, didn't worked. Then I tried `componentDidMount` for same purpose, also didn't worked. After that I tried get song `currentTime` through `audio` element, failed.  So finally i tried just add timer and start it when song is playing and pause it when song is paused. I got confused, could you give me direction what should i be looking for to solve this issue.