Changes for Remove icons task
zero-to-mastery/visual-music pull request #56
Opened 2019-10-28 19:05 UTC by JimBratsos

What I did:
Removed icons
Added links
Fixed the reference to the icons themselves ( github was linkedin and linkedin was github )

2019-10-29 21:09 UTC, ArnasDickus requested changes
Hello, thanks for adding PR. Next time create a PR from your development branch instead of working directly in your development branch. Because:
1) Until this PR is approved, you can't work on any other PR.
2) It shows that 3 participants have worked on this PR. Which is false.

2019-10-29 21:09 UTC, ArnasDickus commented on src/components/LandingPage/sections/SectionThree/SectionThreeIcons/SectionThreeIcons.js
> +            <a href = "https://github.com/zero-to-mastery/visual-music">
Add `target="_blank"`

2019-10-29 21:09 UTC, ArnasDickus commented on src/components/LandingPage/sections/SectionThree/SectionThreeIcons/SectionThreeIcons.js
> +            <a href = "https://www.linkedin.com/company/zerotomastery/">
Add `target="_blank"`

2019-10-30 06:51 UTC, JimBratsos reviewed
Changes requested are completed.

2019-10-30 10:51 UTC, ArnasDickus commented
@JimBratsos Okay, now the only thing that left is you need to fix conflicting files. By updating your branch. Try running on development branch
`git fetch upstream`
`git merge upstream/development` 
you might encounter some conflicts that you need to fix manually, and commit again.

2019-10-30 13:32 UTC, ArnasDickus approved these changes

2019-10-30 16:32 UTC, merged