getting song time from canvas to redux and PlayerBar
zero-to-mastery/visual-music pull request #72
Opened 2019-11-11 15:34 UTC by YogiHa

getting song time from canvas to redux store, and after passing it to PlayerBar component. uncomment the console.log in PlayerBar to see the result

also try to fix Travis issue with grpc dependency

2019-11-11 20:53 UTC, ArnasDickus requested changes
Hello, thanks for adding PR.
There are some console warnings. Also could you fix sectionThreeIcons.js erros. Contributor who supposed to fixed got stuck.
![console errros](https://user-images.githubusercontent.com/38657595/68620062-678c1400-04d5-11ea-94ce-add9fee9d8bf.jpg)

Also Playing a song get's weird animation. I tested with current development branch. It looks normal.  So it must be something on your end.
![playing-song-wierd-animation](https://user-images.githubusercontent.com/38657595/68620306-e1bc9880-04d5-11ea-8a3a-123fc4efd89c.jpg)

2019-11-11 20:53 UTC, ArnasDickus commented on package.json
> +    "grpc": "^1.24.2",
It seems your Travis test fix solution is not working

2019-11-12 06:51 UTC, ArnasDickus commented
@YogiHa Travis bug was fixed in [PR #73](https://github.com/zero-to-mastery/visual-music/pull/73). Please update your branch.

2019-11-12 12:49 UTC, YogiHa commented
@ArnasDickus I will update my package.json as follow PR 73,

and will push when I'll manage to fix sketch, every second the sketch exporting for some reason it restrating

2019-11-13 13:49 UTC, YogiHa commented
opening a new PR due to reworking on this task from other angle

2019-11-13 13:50 UTC, closed without merging