Fix issues
zero-to-mastery/visual-music pull request #84
Opened 2019-11-24 10:08 UTC by matteo1976

Deleted parallax and added animation.
fix responsive interface

2019-11-26 19:15 UTC, ArnasDickus commented
Hello, thanks for adding PR. After approving other PR. You have code conflicts. To fix them, update your current branch.

`git checkout development` - visit development branch
`git fetch upstream development` - get the newest changes from the development branch.
`git merge upstream/development` - merge development branch to your own local branch.
`git checkout fix-issue` - visit your current branch
`git merge upstream/development `- merge development branch changes with your current changes. if you using visual studio you and there are conflicts you will have to deal with it manually. After that the usual

```
git status
git add
git commit -m 'message here'
git push
```

2019-11-29 09:57 UTC, ArnasDickus commented
@matteo1976 How's it going?

2019-11-29 11:01 UTC, matteo1976 commented
Sorry good but I didn't have time to fix , I will try this weekend

Il Ven 29 Nov 2019, 10:57 Arnas <notifications@github.com> ha scritto:

> @matteo1976 <https://github.com/matteo1976> How's it going?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zero-to-mastery/visual-music/pull/84?email_source=notifications&email_token=AHWGORTDWXP6RE4LRHA2WNLQWDRQLA5CNFSM4JQ6LCV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFONKYQ#issuecomment-559732066>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHWGORR7ZMILNENC3MI7IMLQWDRQLANCNFSM4JQ6LCVQ>
> .
>

2019-12-02 11:29 UTC, ArnasDickus commented
@matteo1976 How's it going?

2019-12-03 07:44 UTC, matteo1976 commented
I will work and PR again today in the afternoon .... sorry for the delay

Il Lun 2 Dic 2019, 12:29 Arnas <notifications@github.com> ha scritto:

> @matteo1976 <https://github.com/matteo1976> How's it going?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zero-to-mastery/visual-music/pull/84?email_source=notifications&email_token=AHWGORRKBNF46JJMWSXWPSTQWTWR5A5CNFSM4JQ6LCV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFTF33Y#issuecomment-560356847>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHWGORWZZLBZKWYVSHNOM5DQWTWR5ANCNFSM4JQ6LCVQ>
> .
>

2019-12-03 14:17 UTC, matteo1976 commented
Did

2019-12-03 14:21 UTC, matteo1976 commented
still, have some errors with checks ... I don't know what I have to do.

2019-12-04 18:04 UTC, ArnasDickus commented
@matteo1976 The error Cannot find module: 'react-reveal'. Make sure this package is installed.

2019-12-04 19:31 UTC, matteo1976 commented
ok tomorrow i try to fix and I had realised that I have to clean a bit the
code

Il Mer 4 Dic 2019, 19:04 Arnas <notifications@github.com> ha scritto:

> @matteo1976 <https://github.com/matteo1976> The error Cannot find module:
> 'react-reveal'. Make sure this package is installed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zero-to-mastery/visual-music/pull/84?email_source=notifications&email_token=AHWGORSJRRSZKHME3NOEXGTQW7WMRA5CNFSM4JQ6LCV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF56TOQ#issuecomment-561768890>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHWGORSV6HDZ5B45PIM75JDQW7WMRANCNFSM4JQ6LCVQ>
> .
>

2019-12-05 16:33 UTC, matteo1976 commented
I did. now could be work

Il giorno mer 4 dic 2019 alle ore 20:31 matteo Angelotti <
matteoangelotti.ch@gmail.com> ha scritto:

> ok tomorrow i try to fix and I had realised that I have to clean a bit the
> code
>
> Il Mer 4 Dic 2019, 19:04 Arnas <notifications@github.com> ha scritto:
>
>> @matteo1976 <https://github.com/matteo1976> The error Cannot find
>> module: 'react-reveal'. Make sure this package is installed.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/zero-to-mastery/visual-music/pull/84?email_source=notifications&email_token=AHWGORSJRRSZKHME3NOEXGTQW7WMRA5CNFSM4JQ6LCV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF56TOQ#issuecomment-561768890>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AHWGORSV6HDZ5B45PIM75JDQW7WMRANCNFSM4JQ6LCVQ>
>> .
>>
>

2019-12-07 12:07 UTC, ArnasDickus requested changes
Hello thanks for adding PR.

1) Grammer mistake favoriet - favorite.
2) On mobile add some space between would you like to write to us and contact.
![contact](https://user-images.githubusercontent.com/38657595/70374295-7bbb0980-18f9-11ea-8d0d-ebe20540b2e1.jpg)

2019-12-07 12:07 UTC, ArnasDickus commented on src/pages/LandingPage/ContactComponents/FormComponents/ContactForm.module.scss
> +    // width: 66%;
If code is not in use delete it, instead of commenting out.

2019-12-07 12:07 UTC, ArnasDickus commented on src/pages/LandingPage/ContactComponents/FormComponents/ContactForm.module.scss
> +            width: 100px;
Instead of px use rem.

2019-12-07 12:07 UTC, ArnasDickus commented on src/pages/LandingPage/ContactComponents/FormComponents/ContactForm.js
> +                <Button type="submit" text="Send" btnClass="signUp" style={{width:'100px'}} />
Instead of px use rem. For accessibility reasons.

2019-12-07 12:07 UTC, ArnasDickus commented on src/pages/LandingPage/ContactComponents/FormComponents/ContactForm.module.scss
> +    // align-items: center;
remove unused code.

2019-12-07 12:07 UTC, ArnasDickus commented on src/pages/LandingPage/LandingPage.js
> +                                    An app that converts your favoriet music pieces into visual
Grammar mistake favouriet -> favourite

2019-12-09 13:26 UTC, matteo1976 commented
All did

2019-12-10 18:43 UTC, ArnasDickus approved these changes
Alright, approving

2019-12-10 18:43 UTC, merged