Feature/screenshot (front-end only)
zero-to-mastery/visual-music pull request #89
Opened 2019-12-03 06:32 UTC by michaelbretagne

- Take a screenshot when the photo icon is clicked.
- Display the screenshot modal when the screenshot image has been dispatched.
- Allow the user to click on social media icons to share their screenshot. (front-end only, for now, the sharing part is not coded).
- Implement success/error modal after a screenshot is shared (front-end only, so now the response is hardcoded to true for Instagram and false for the other social media).
- Modify electric-guitar.svg and electric-guitar-success.svg. It wasn't showing properly with the clip-path element.
- Add social icons (downloaded SVGs from font-awesome)
- Add left-curve-arrow.svg (Designed by Nab)
- Modify the fill color of some SVGs so we can easily change their colors with CSS (darker color when they are active/click).

2019-12-06 19:28 UTC, ArnasDickus requested changes
Hello, thanks for adding PR. So everything looks good. But I see a few problems:

1) A black background is out of place. I suggest adding the same BG as player background: #595757
2) As you already mentioned there is no sharing functionality. Since this PR is already big, you don't need to implement it.

2019-12-06 19:28 UTC, ArnasDickus commented on src/components/ScreenshotModal/BackToPlayer.js
> +            <p>Back to PLayer</p>
Back to Player not PLayer

2019-12-07 04:19 UTC, michaelbretagne commented on src/components/ScreenshotModal/BackToPlayer.js
> +            <p>Back to PLayer</p>
Good catch ;-)

2019-12-07 04:25 UTC, michaelbretagne commented
Added global variable into /globalScss/variables.scss
Change ScreenshotModal.js, Error.js and Success.js background color to #595757 ($grey).
Fix typo in BackToPlayer.js.

2019-12-07 11:39 UTC, ArnasDickus approved these changes

2019-12-07 11:39 UTC, merged